package com.ProjetoWheels.enums.usuarios;

public enum EstadoUsuario {

    ESCOLHENDO_TIPO,
    ESCOLHENDO_MODELO,
    AGUARDANDO_ESCOLHA_DURACAO_OU_MAIS,
    ESCOLHANDO_DIAS,
    AGUARDANDO_EMAIL,
    ESCOLHENDO_PAGAMENTO,
    FINALIZANDO
}

